name = "twitch-cloudflare-storage"
main = "src/index.js"
compatibility_date = "2024-01-29"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "config"
id = "8b40bb01bf4340c2b62d0debd144d9b2"

[[r2_buckets]]
binding = "storage"
bucket_name = "sugoi-web-services"
jurisdiction = "eu"