name = "twitch-cloudflare-storage"
main = "src/index.js"
compatibility_date = "2024-01-29"
compatibility_flags = [ "nodejs_compat" ]
route = "ts.sugoidogo.com"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "config"
id = "8b40bb01bf4340c2b62d0debd144d9b2"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "storage"
bucket_name = "sugoi-web-services"
jurisdiction = "eu"