on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          append_body: true
          tag_name: "${{ inputs.tag }}"